### ISSUE TITLE
Documentation bug: "null" or "empty"?

### ISSUE THREAD

**Issue by cdown** [vladc/ip-api.com#1]
On http://ip-api.com/docs/api:returned_values#field_generator, it says:

> In case we don't have data on a specific field, the returned value will be null (empty)

This sentence is confusing, because in JSON, `null` and "empty" (`""`) are totally different things:

``` python
In [4]: json.loads('null') is None
Out[4]: True

In [5]: json.loads('""') is None
Out[5]: False
```

Which one will happen if the field -- for example, the timezone -- is missing? Will it be an empty string, or a null?

**Comment by vladc** [comment]
You're absolutely right!
I wish I could change the API to return an actual null, and also return true/false for the status field, but due to compatibility reasons I can't.

I'll update the docs and remove the null mention.

**Comment by vladc** [comment]
The page has been [updated](http://ip-api.com/docs/api:returned_values#return_values), please have a look.

**Comment by cdown** [comment]
Looks good to me, thanks!
